### ISSUE TITLE
domains and subdomains for recruitee and palo alto

### ISSUE THREAD

**Issue by AliML111** [AliKhadivi/sanctioned-domains#1]
Add these too:
Recruitee platform:
usercentrics.eu
*.usercentrics.eu
recruitee.com
*.recruitee.com

Palo alto:
*.paloaltonetworks.com
paloaltonetworks.com

Cloudfront CDN:
*.cloudfront.net

**Comment by AliKhadivi** [comment]
Hi.
I added `Recruitee platform` and `Palo alto`, but I can't add the wildcard domain of `Cloudfront` because some subdomains of `cloudfront.net` are not sanctioned.
Thank you for contributing in my project.
Bye
